SELECT 
    *,
    CASE WHEN CANCEL_AT_TS IS NOT NULL THEN TRUE ELSE FALSE END as IS_CANCELED,
    CASE WHEN walker_id IS NOT NULL THEN TRUE ELSE FALSE END as IS_EXECUTED,
    CASE WHEN refund > 0 THEN TRUE ELSE FALSE END IS_REFUNDED
FROM {{ ref('int_walk') }} 