SELECT 
    _FILE,
    _LINE,
    _MODIFIED AS _MODIFIED_TS,
    _FIVETRAN_SYNCED AS _FIVETRAN_SYNCED_TS,
    CAST(REPLACE(DATE, 'dd ', '') AS DATE) AS EXPENSES_DATE,
    FULL_TIME_SALARIES AS SALARIES_COST,
    TOOLS AS TOOLS_COST,
    OTHER_EXPENSES AS OTHER_COST
FROM {{ source('google_drive', 'expenses') }}