SELECT
    _FILE,
    _LINE,
    _MODIFIED,
    _fivetran_synced,
    ADDRESS AS CLIENT_ADDRESS,
    CITY AS CLIENT_CITY,
    CAST(CLIENT_ID AS STRING) AS CLIENT_ID,
    PET_NAME,
    REQUEST_DURATION AS DURATION_MIN,
    REQUEST_AT,
    PHONE,
    NAME AS CLIENT_NAME,
    REQUEST_DAY_FROM,
    CAST(PET_ID AS STRING) AS PET_ID
FROM {{ source('box', 'requests') }}