
SELECT
    _FILE,
    _LINE,
    _MODIFIED,
    _fivetran_synced,
    CLIENT_ID,
    WALKER_ID,
    PET_ID,
    CAST(REQUEST_DAY_FROM AS TIMESTAMP WITHOUT TIME ZONE) AS REQUEST_DAY_FROM,
    CAST(REQUEST_DURATION AS NUMERIC) AS REQUEST_DURATION_MIN,
    CAST(PRICE_PAID AS DOUBLE) AS PRICE_PAID,
    CAST(TAXES_PAID AS DOUBLE) AS TAXES_PAID,
    CAST(PAID_TO_WALKER AS DOUBLE) AS PAID_TO_WALKER,
    CAST(REFUND AS DOUBLE) AS REFUND
FROM {{source('box', 'walks')}}
WHERE CLIENT_ID != 'NA'