version: 2

sources:
  - name: box
    database: LOAD
    schema: BOX
    tables:
      - name: requests
        freshness:
          warn_after: {count: 1, period: day}
          error_after: {count: 5, period: day}
        loaded_at_field: _fivetran_synced
      - name: cancellations
      - name: walks