version: 2

sources:
  - name: box
    database: LOAD
    schema: BOX
    tables:
      - name: requests
  - name: google_analytics
    database: LOAD
    schema: GOOGLE_ANALYTICS
    tables:
      - name: demographic_city_report